language: php

php:
 - 5.3
 - 5.4
 - 5.5

before_script:
  - composer install --dev --prefer-source

script: ./vendor/bin/phpunit --coverage-text --coverage-clover ./build/logs/clover.xml

after_script: php vendor/bin/coveralls

notifications:
  email:
    recipients:
      - haeuslmann@gmail.com
    on_success: never
    on_failure: always
